// File generated by "TGA_Pow2_32bit_To_TextureArray.exe" [Version 0.4a] Author: L.Norri CD GX1/GX2 Fullsail University.
// A full MipMap chain is only generated for images that are powers of 2. (Files with no mip chain have "1" Level)
// MipMap generation ends once width or height reaches 1 pixel across.

#ifndef _miptest_H_
#define _miptest_H_

const unsigned int miptest_width = 512;
const unsigned int miptest_height = 512;

const unsigned int miptest_numlevels = 10;

// All Pixel Data within this file is UNCOMPRESSED 32BIT BGRA(Blue8,Green8,Red8,Alpha8) COLOR DATA STORED TOP TO BOTTOM IN A 1D ARRAY!
// To correctly access a pixel you must use the following offset array in conjunction with 2D->1D array indexing. (y*width+x)

const unsigned int miptest_leveloffsets[miptest_numlevels] = { 0, 64, 80, 84 };

const unsigned int miptest_pixels[85] =
{
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00, 0xff00ff00,
	0xff0000ff, 0xff0000ff, 0xff0000ff, 0xff0000ff,
	0xff0000ff, 0xff0000ff, 0xff0000ff, 0xff0000ff,
	0xff0000ff, 0xff0000ff, 0xff0000ff, 0xff0000ff,
	0xff0000ff, 0xff0000ff, 0xff0000ff, 0xff0000ff,
	0xffffff00, 0xffffff00,
	0xffffff00, 0xffffff00,
	0xffffffff,
};
#endif